import type {
  DashboardData,
  DrugLabelFlag,
  InteractionSignal,
  SubgroupSignal,
} from "./types";

const signalScores = [
  ["SEMAGLUTIDE", "NAUSEA", "GLP-1 receptor agonist", 18742, 4.8, 4.6, 5.1, 4.1, 920.6, 0.13, 2.84, true],
  ["SEMAGLUTIDE", "VOMITING", "GLP-1 receptor agonist", 12904, 4.2, 4.0, 4.5, 3.8, 684.3, 0.16, 2.61, true],
  ["SEMAGLUTIDE", "PANCREATITIS", "GLP-1 receptor agonist", 1812, 2.7, 2.4, 3.1, 2.3, 118.5, 0.42, 1.83, true],
  ["SEMAGLUTIDE", "ILEUS", "GLP-1 receptor agonist", 462, 3.4, 2.8, 4.2, 2.8, 96.2, 0.51, 1.95, true],
  ["TIRZEPATIDE", "NAUSEA", "Dual GIP/GLP-1 agonist", 9630, 4.1, 3.8, 4.4, 3.5, 412.8, 0.12, 2.42, true],
  ["TIRZEPATIDE", "VOMITING", "Dual GIP/GLP-1 agonist", 6816, 3.9, 3.6, 4.2, 3.3, 356.7, 0.14, 2.31, true],
  ["TIRZEPATIDE", "GASTROPARESIS", "Dual GIP/GLP-1 agonist", 588, 5.6, 4.7, 6.8, 4.7, 156.4, 0.37, 2.38, true],
  ["LIRAGLUTIDE", "PANCREATITIS", "GLP-1 receptor agonist", 1344, 2.3, 2.0, 2.7, 2.0, 88.4, 0.48, 1.54, true],
  ["DULAGLUTIDE", "CHONDRITIS", "GLP-1 receptor agonist", 86, 1.8, 1.2, 2.6, 1.4, 12.1, 0.36, 0.72, false],
  ["EXENATIDE", "HYPOGLYCAEMIA", "GLP-1 receptor agonist", 1078, 1.6, 1.4, 1.9, 1.5, 41.4, 0.33, 0.94, false],
  ["METFORMIN", "LACTIC ACIDOSIS", "Biguanide", 2110, 5.2, 4.7, 5.8, 4.5, 280.6, 0.66, 2.46, true],
  ["INSULIN GLARGINE", "HYPOGLYCAEMIA", "Basal insulin", 24510, 6.8, 6.4, 7.2, 5.9, 1180.2, 0.31, 3.12, true],
] as const;

const emergingSignals = [
  ["TIRZEPATIDE", "GASTROPARESIS", "Dual GIP/GLP-1 agonist", 146, 38, 2.84, 4.1, 0.37, 0.91, "High", 12, true, "2026Q2"],
  ["SEMAGLUTIDE", "ILEUS", "GLP-1 receptor agonist", 118, 42, 1.81, 3.3, 0.51, 0.86, "High", 18, true, "2026Q2"],
  ["SEMAGLUTIDE", "PANCREATITIS", "GLP-1 receptor agonist", 390, 248, 0.57, 2.0, 0.42, 0.74, "Moderate", 34, true, "2026Q2"],
  ["METFORMIN", "LACTIC ACIDOSIS", "Biguanide", 291, 210, 0.39, 1.5, 0.66, 0.67, "Moderate", 41, true, "2026Q2"],
  ["TIRZEPATIDE", "VOMITING", "Dual GIP/GLP-1 agonist", 1620, 1180, 0.37, 1.6, 0.14, 0.62, "Moderate", 9, true, "2026Q2"],
  ["DULAGLUTIDE", "CHONDRITIS", "GLP-1 receptor agonist", 22, 18, 0.22, 0.5, 0.36, 0.28, "Low", 1, false, "2026Q2"],
] as const;

const classOf = (drug: string): string =>
  (signalScores.find((r) => r[0] === drug)?.[2] as string | undefined) ?? "Metabolic agent";

function interaction(
  drug_a: string,
  drug_b: string,
  adverse_event: string,
  co_reports: number,
  pair_event_reports: number,
  ror_comb: number,
  ci_lo: number,
  ci_hi: number,
  ror_a: number,
  ror_b: number,
): InteractionSignal {
  const single_max = Math.max(ror_a, ror_b);
  const ratio = ror_comb / single_max;
  return {
    drug_a,
    drug_b,
    adverse_event,
    co_reports,
    pair_event_reports,
    ror_combination: ror_comb,
    ror_ci_lower: ci_lo,
    ror_ci_upper: ci_hi,
    prr_combination: Number((ror_comb * 0.82).toFixed(2)),
    chi_square: Number((pair_event_reports * 0.6).toFixed(1)),
    ror_drug_a: ror_a,
    ror_drug_b: ror_b,
    single_max_ror: single_max,
    comparable: true,
    interaction_ratio: Number(ratio.toFixed(2)),
    interaction_flag: ci_lo > 1 && ratio >= 2,
  };
}

function subgroup(
  drug: string,
  adverse_event: string,
  subgroup_type: "sex" | "age",
  sg: string,
  stratum_reports: number,
  overall_ror: number,
  ror: number,
  ci_lo: number,
  ci_hi: number,
): SubgroupSignal {
  return {
    drug_name_normalized: drug,
    drug_class: classOf(drug),
    adverse_event,
    subgroup_type,
    subgroup: sg,
    stratum_reports,
    stratum_population: Math.round(stratum_reports * 420 + 50000),
    ror,
    ror_ci_lower: ci_lo,
    ror_ci_upper: ci_hi,
    prr: Number((ror * 0.85).toFixed(2)),
    chi_square: Number((stratum_reports * 0.05).toFixed(1)),
    overall_ror,
  };
}

function label(
  drug: string,
  adverse_event: string,
  labeled: boolean,
  section: string | null,
): DrugLabelFlag {
  return {
    drug_name_normalized: drug,
    adverse_event,
    labeled_event: labeled,
    label_section: section,
    label_found: true,
    label_status: labeled ? "labeled" : "novel",
    novel_flag: !labeled,
  };
}

export const demoData: DashboardData = {
  generated_at: "2026-06-20T12:00:00Z",
  data_source: "demo",
  signal_scores: signalScores.map((row) => ({
    drug_name_normalized: row[0],
    adverse_event: row[1],
    drug_class: row[2],
    a_drug_event: row[3],
    ror: row[4],
    ror_ci_lower: row[5],
    ror_ci_upper: row[6],
    prr: row[7],
    chi_square: row[8],
    seriousness_rate: row[9],
    bayesian_shrunken_score: row[10],
    disproportionality_flag: row[11],
  })),
  emerging_signals: emergingSignals.map((row) => ({
    drug_name_normalized: row[0],
    adverse_event: row[1],
    drug_class: row[2],
    current_count: row[3],
    trailing_baseline_count: row[4],
    percent_change: row[5],
    anomaly_score: row[6],
    seriousness_rate: row[7],
    priority_score: row[8],
    priority_level: row[9],
    literature_support_count: row[10],
    nhanes_context_available: row[11],
    current_quarter: row[12],
  })),
  nhanes_population_context: [
    {
      medication_name_normalized: "SEMAGLUTIDE",
      drug_class: "GLP-1 receptor agonist",
      weighted_prevalence: 0.021,
      unweighted_sample_count: 134,
      median_age: 58,
      female_percent: 57,
      bmi_ge_30_percent: 71,
      diabetes_percent: 63,
      hba1c_median: 6.8,
      small_n_flag: false,
      very_small_n_flag: false,
      survey_cycle: "2021-2023",
      weight_variable_used: "WTMEC2YR",
    },
    {
      medication_name_normalized: "TIRZEPATIDE",
      drug_class: "Dual GIP/GLP-1 agonist",
      weighted_prevalence: 0.008,
      unweighted_sample_count: 42,
      median_age: 56,
      female_percent: 61,
      bmi_ge_30_percent: 77,
      diabetes_percent: 69,
      hba1c_median: 7.1,
      small_n_flag: true,
      very_small_n_flag: false,
      survey_cycle: "2021-2023",
      weight_variable_used: "WTMEC2YR",
    },
    {
      medication_name_normalized: "METFORMIN",
      drug_class: "Biguanide",
      weighted_prevalence: 0.074,
      unweighted_sample_count: 624,
      median_age: 62,
      female_percent: 49,
      bmi_ge_30_percent: 58,
      diabetes_percent: 94,
      hba1c_median: 7.0,
      small_n_flag: false,
      very_small_n_flag: false,
      survey_cycle: "2021-2023",
      weight_variable_used: "WTMEC2YR",
    },
  ],
  pubmed_evidence: [
    {
      drug_name_normalized: "SEMAGLUTIDE",
      adverse_event: "PANCREATITIS",
      title: "Pancreatic safety signals reported with incretin-based therapies",
      journal: "Pharmacoepidemiology and Drug Safety",
      publication_year: 2025,
      pmid: "40123456",
      relevance_score: 0.91,
      url: "https://pubmed.ncbi.nlm.nih.gov/40123456/",
      evidence_snippet: "Title and abstract terms overlap with the selected drug-event signal.",
    },
    {
      drug_name_normalized: "TIRZEPATIDE",
      adverse_event: "GASTROPARESIS",
      title: "Gastrointestinal tolerability in dual incretin agonist therapy",
      journal: "Diabetes Care",
      publication_year: 2026,
      pmid: "40999888",
      relevance_score: 0.86,
      url: "https://pubmed.ncbi.nlm.nih.gov/40999888/",
      evidence_snippet: "Retrieved article discusses delayed gastric emptying and related terms.",
    },
    {
      drug_name_normalized: "METFORMIN",
      adverse_event: "LACTIC ACIDOSIS",
      title: "Risk factors for metformin-associated lactic acidosis",
      journal: "Clinical Pharmacology",
      publication_year: 2024,
      pmid: "38900123",
      relevance_score: 0.89,
      url: "https://pubmed.ncbi.nlm.nih.gov/38900123/",
      evidence_snippet: "Clinical context supports known pharmacovigilance monitoring relevance.",
    },
  ],
  pipeline_health: [
    {
      run_id: "demo-2026-06-20",
      source: "openFDA",
      source_period: "2026Q2",
      run_timestamp: "2026-06-20T12:00:00Z",
      status: "pass",
      rows_raw: 1842500,
      rows_silver: 612440,
      rows_gold: 92136,
      failed_checks: 0,
      warning_checks: 2,
      estimated_cost_usd: 3.42,
      notes: "Demo payload. Connect NEXT_PUBLIC_PHARMASIGNAL_API_BASE_URL to read AWS-backed data.",
    },
  ],
  data_quality_checks: [
    {
      table: "signal_scores",
      check: "minimum required columns",
      category: "schema",
      status: "pass",
      detail: "All dashboard columns are present.",
    },
    {
      table: "nhanes_population_context",
      check: "small sample warning",
      category: "stability",
      status: "warn",
      detail: "Tirzepatide population estimates have a small unweighted sample.",
    },
  ],
  interaction_signals: [
    // GLP-1 / dual-incretin + insulin → hypoglycaemia is the classic additive synergy.
    interaction("SEMAGLUTIDE", "INSULIN GLARGINE", "HYPOGLYCAEMIA", 1840, 612, 14.2, 12.8, 15.7, 3.4, 6.8),
    interaction("TIRZEPATIDE", "INSULIN GLARGINE", "HYPOGLYCAEMIA", 980, 388, 15.0, 13.2, 17.1, 3.1, 6.8),
    interaction("SEMAGLUTIDE", "METFORMIN", "DIARRHOEA", 3120, 1042, 5.4, 4.9, 5.9, 2.4, 2.1),
    interaction("LIRAGLUTIDE", "INSULIN GLARGINE", "HYPOGLYCAEMIA", 540, 191, 8.1, 6.9, 9.5, 1.7, 6.8),
    interaction("SEMAGLUTIDE", "METFORMIN", "NAUSEA", 3120, 1610, 5.1, 4.8, 5.4, 4.8, 2.0),
    interaction("TIRZEPATIDE", "METFORMIN", "VOMITING", 1280, 470, 4.4, 4.0, 4.9, 3.9, 1.9),
  ],
  subgroup_signals: [
    // SEMAGLUTIDE · NAUSEA — concentrated in women, modest age gradient.
    subgroup("SEMAGLUTIDE", "NAUSEA", "sex", "female", 11240, 4.8, 5.6, 5.3, 5.9),
    subgroup("SEMAGLUTIDE", "NAUSEA", "sex", "male", 6890, 4.8, 4.1, 3.8, 4.4),
    subgroup("SEMAGLUTIDE", "NAUSEA", "age", "18-64", 12880, 4.8, 5.0, 4.7, 5.3),
    subgroup("SEMAGLUTIDE", "NAUSEA", "age", "65+", 5210, 4.8, 4.3, 3.9, 4.7),
    // SEMAGLUTIDE · PANCREATITIS — concentrated in 65+.
    subgroup("SEMAGLUTIDE", "PANCREATITIS", "sex", "female", 980, 2.7, 2.6, 2.2, 3.1),
    subgroup("SEMAGLUTIDE", "PANCREATITIS", "sex", "male", 832, 2.7, 2.9, 2.4, 3.5),
    subgroup("SEMAGLUTIDE", "PANCREATITIS", "age", "18-64", 1120, 2.7, 2.4, 2.0, 2.9),
    subgroup("SEMAGLUTIDE", "PANCREATITIS", "age", "65+", 692, 2.7, 4.1, 3.3, 5.1),
    // TIRZEPATIDE · GASTROPARESIS — strong female concentration.
    subgroup("TIRZEPATIDE", "GASTROPARESIS", "sex", "female", 392, 5.6, 7.4, 5.9, 9.3),
    subgroup("TIRZEPATIDE", "GASTROPARESIS", "sex", "male", 196, 5.6, 3.6, 2.6, 5.0),
    subgroup("TIRZEPATIDE", "GASTROPARESIS", "age", "18-64", 470, 5.6, 5.9, 4.7, 7.4),
    subgroup("TIRZEPATIDE", "GASTROPARESIS", "age", "65+", 118, 5.6, 4.8, 3.2, 7.2),
    // INSULIN GLARGINE · HYPOGLYCAEMIA — concentrated in 65+.
    subgroup("INSULIN GLARGINE", "HYPOGLYCAEMIA", "sex", "female", 12010, 6.8, 6.5, 6.0, 7.0),
    subgroup("INSULIN GLARGINE", "HYPOGLYCAEMIA", "sex", "male", 12500, 6.8, 7.1, 6.6, 7.7),
    subgroup("INSULIN GLARGINE", "HYPOGLYCAEMIA", "age", "18-64", 13200, 6.8, 5.9, 5.5, 6.3),
    subgroup("INSULIN GLARGINE", "HYPOGLYCAEMIA", "age", "65+", 11310, 6.8, 8.7, 8.0, 9.5),
  ],
  drug_label_flags: [
    label("SEMAGLUTIDE", "NAUSEA", true, "Adverse Reactions"),
    label("SEMAGLUTIDE", "VOMITING", true, "Adverse Reactions"),
    label("SEMAGLUTIDE", "PANCREATITIS", true, "Warnings and Precautions"),
    label("SEMAGLUTIDE", "ILEUS", false, null), // novel — postmarketing signal not in label
    label("TIRZEPATIDE", "NAUSEA", true, "Adverse Reactions"),
    label("TIRZEPATIDE", "VOMITING", true, "Adverse Reactions"),
    label("TIRZEPATIDE", "GASTROPARESIS", false, null), // novel
    label("LIRAGLUTIDE", "PANCREATITIS", true, "Warnings and Precautions"),
    label("DULAGLUTIDE", "CHONDRITIS", false, null), // novel (low signal)
    label("EXENATIDE", "HYPOGLYCAEMIA", true, "Adverse Reactions"),
    label("METFORMIN", "LACTIC ACIDOSIS", true, "Boxed Warning"),
    label("INSULIN GLARGINE", "HYPOGLYCAEMIA", true, "Warnings and Precautions"),
  ],
};
